name = "SatelliteTypes"
uuid = "104c01f3-edb2-4478-93b7-cdaa98dd5680"
authors = ["Joshua Billson"]
version = "1.0.0-DEV"

[deps]
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
ReadableRegex = "cbbcb084-453d-4c4c-b292-e315607ba6a4"

[compat]
Pipe = "1"
ReadableRegex = "0.3"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
