name = "SatelliteDataSources"
uuid = "104c01f3-edb2-4478-93b7-cdaa98dd5680"
authors = ["Joshua Billson"]
version = "0.0.1"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
ReadableRegex = "cbbcb084-453d-4c4c-b292-e315607ba6a4"

[weakdeps]
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"

[extensions]
SatelliteDataSourcesRastersExt = "Rasters"

[compat]
OrderedCollections = "1"
Pipe = "1"
Rasters = "0.8"
ReadableRegex = "0.3"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
